//Create
POST http://localhost:5000/comments HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlbmRlcjY3OTUxQWRtaW4yMTIyQGdtYWlsLmNvbSIsImlkIjoyNCwicm9sZXMiOlt7ImlkIjoyLCJ2YWx1ZSI6IkFETUlOIiwiZGVzY3JpcHRpb24iOiJWZXJ5IGltcG9ydGFudCByb2xlIiwiY3JlYXRlZEF0IjoiMjAyMi0wOS0xNlQwOToyOTozMS44NDlaIiwidXBkYXRlZEF0IjoiMjAyMi0wOS0xNlQwOToyOTozMS44NDlaIiwiVXNlclJvbGVzIjp7ImlkIjoyLCJyb2xlSWQiOjIsInVzZXJJZCI6MjR9fV0sImlhdCI6MTY2MzY2MDM5MiwiZXhwIjoxNjYzNzQ2NzkyfQ.tQyDt5S87RFXQS4AlYuWh9NpnoUAS1d3uisq5WD17YE

{
    "message": "test message",
    "productId": 2
}

###

//Get all
GET http://localhost:5000/comments HTTP/1.1

###

//Get by id
GET http://localhost:5000/comments/2 HTTP/1.1

###

//Get by user id
GET http://localhost:5000/comments/userId/2 HTTP/1.1

###

//Get by product id
GET http://localhost:5000/comments/productId/2 HTTP/1.1

###


//Delete by id
DELETE  http://localhost:5000/comments/1 HTTP/1.1

###

//Update by id
PATCH   http://localhost:5000/comments/2 HTTP/1.1
content-type: application/json

{
    "message": "test message2"
}
### 